### ISSUE TITLE
Installation Questions

### ISSUE THREAD

**Issue by spadavec** [deweylab/MetaSRA-API-backend#1]
Hi, the website seems to be running into issues, so I wanted to re-host this myself and am running into some questions during installation:

> Make sure onto_lib for python3 is in the python path, and all OBO ontology files required by onto_lib are present. (For now, the easiest way to accomplish this is to copy onto_lib and the OBO files into /build-db-script/onto_lib . You might have to edit the onto_lib python files to tell it where to look for the OBO files.)

Where are these files located, or where can they be obtained from? I don't see any reference to these files anywhere. 

> SRA metadata subset DB : SQLite file : a byproduct of the MetaSRA pipeline

Where is this file located? 

Very excited to get this up and running--thanks for the help!

**Comment by mziegler** [comment]
Thanks for alerting us to issues with the website!  We're working on figuring it out now and should hopefully have it up again soon.

Here are the OBO files:
https://github.com/deweylab/MetaSRA-pipeline/tree/master/map_sra_to_ontology/obo

As far as I can find, we haven't published the SRA subset DB file anywhere - you can get it from running the MetaSRA pipeline.  @mbernste would know better.
https://github.com/deweylab/MetaSRA-pipeline/tree/master/map_sra_to_ontology

**Comment by mbernste** [comment]
The website is back up and running! 

As far as doing a local installation of the website, I can definitely upload the SRA subset DB in the coming days. This database is a subset of the SRAdb (https://www.bioconductor.org/packages/release/bioc/html/SRAdb.html) that we use in the back-end of the website.
