### ISSUE TITLE
Allow for logical operations in term selection

### ISSUE THREAD

**Issue by spadavec** [deweylab/MetaSRA-API-backend#2]
It would be really useful if you could allow for logical combinations of terms. For example, if I wanted to find all samples that were either RBCs, OR Monocytes, OR Granulocytes. Currently I can make multiple queries with the API and staple them all together, but it would be great if the API/website allowed for this natively!

**Comment by mbernste** [comment]
Thanks for the feedback! The ability to make Boolean queries would indeed be a useful feature. We will look into implementing that on the next version of the website
