### ISSUE TITLE
API Not respecting 'sampletype' flag

### ISSUE THREAD

**Issue by spadavec** [deweylab/MetaSRA-API-backend#3]
When I attempt to use the 'sampletype' flag via the API, it doesn't seem to return the subset of sampletype only--it seems to just return all of the samples. 

For example:

```http://metasra.biostat.wisc.edu/api/v01/samples.csv?and=CL:0000763&not=EFO:0000727,DOID:4```

and 

```http://metasra.biostat.wisc.edu/api/v01/samples.csv?and=CL:0000763&not=EFO:0000727,DOID:4&sampletype=cell%20line```

return exactly the same number of samples. Is there a way to respect the sampletype designated?

**Comment by cndewey** [comment]
When I open these URLs via my browser I get different results, with the latter only returning cell line samples.  Could you please double check your results?
