### ISSUE TITLE
MetaSRA API Down

### ISSUE THREAD

**Issue by spadavec** [deweylab/MetaSRA-API-backend#4]
After posting to the API route for json.samples, I keep getting 502s. Furhtermore, when you are on the metasra website and try to enter search terms, it keeps claiming that it can't connect with the following:
```
Error: we had a problem processing your search. Please check your network connection, refresh the page, or try again 
```

**Comment by mbernste** [comment]
Thanks for alerting us to this issue. I've just restarted the server and it looks like it's back online.

**Comment by spadavec** [comment]
@mbernste Thanks for the quick turnaround! I'm working on hosting an internal version of this so I won't have to bother you again :)
