### ISSUE TITLE
Differences between local query and website query

### ISSUE THREAD

**Issue by spadavec** [deweylab/MetaSRA-API-backend#5]
I downloaded the metasra JSON file you provide ( ), and tried to replicate the results I get via your service online. I used the following snippet to search for all samples that match a DOID term: 

```python
import json 

example_ontology = 'DOID:9119'
samples = []

with open('../datasets/metasra.v1-5.json') as json_file:
    data = json.load(json_file) 

for sample in data:
    if example_ontology in data[sample]['mapped ontology terms']:
        samples.append(sample)

print(len(samples))
```
For the DOID term 9119, I get 756 samples, but if I use the online service, it returns 903 samples. Do  you know why I'm seeing this discrepancy, and how to address it?

**Comment by spadavec** [comment]
It appears your backend also looks for child DOID terms for a given DOID term, which increases the sample counts. Is there an automated way to grab all these child terms?

**Comment by mbernste** [comment]
Hi, yes the backend should return not only samples labelled with the query ontology term, but also samples labelled with any descendent of the query ontology term.  As far as an automated way to query the ontology for all descendants, there is not a great way to do that at the moment via the MetaSRA.  

If it's any help at all, I can point you to the MetaSRA code that manages the ontology (I tried to decouple it from the MetaSRA pipeline itself and placed it into its own repo): https://github.com/mbernste/onto_lib.  Unfortunately, it is not currently well-documented.

**Comment by spadavec** [comment]
@mbernste awesome, thanks! For now, it appears that we have to download the entire ontology JSON, and search for edges of a given terms, and collect the DOID terms that are children of a given term. Thanks!
